[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
    

# Solidity compiler version
solc_version = "0.8.20"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Via IR for better optimization (optional but recommended)
via_ir = false

# Gas reports
gas_reports = ["*"]

# Formatter
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# RPC endpoints
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

# Etherscan API keys for verification
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

